---

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  become: yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'virtualenv', 'python3-setuptools']
  become: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: yes

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  become: yes

- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  become: yes

